// IMPORT THE RANDOM DELAY FUNCTION //


/*
  WRITE A FUNCTION THAT GENERATES 10 CALLS TO THE RANDOM DELAY FUNCTION
  CONSOLE LOG EACH (INDEX, RESPONSE) IN THE SAME SEQUENCE THE CALLS WERE MADE
    -- MEANING THE FIRST RANDOM DELAY IS 3 SECONDS, THE NEXT IS 5 SECONDS,
       THAT IS THE ORDER THEY SHOULD BE EXECUTED
    -- EX (1, 4)
          (2, 2)
          (3, 10)

          (INDEX, RESPONSE)


  ENSURE TO EXIT THE SCRIPT AT THE END OF EXECUTION
*/
